### ISSUE TITLE
실행이 안됩니다.

### ISSUE THREAD

**Issue by Hhhh8** [lovit/customized_konlpy#18]
anaconda prompt 로 git clone 후 pip install 해주었습니다.
이후 jupyter notebook에서 아래와 같이 실행하였으나 에러가 납니다.
![image](https://user-images.githubusercontent.com/27391963/52758429-97dc7a00-304b-11e9-877e-b835297464e2.png)

단순히 import만 할 시에는 error가 없는데 왜 그럴까요 .. 
답변 부탁드립니다.

**Comment by dharma2018** [comment]
![image](https://user-images.githubusercontent.com/38173139/54371869-85db0f00-46bd-11e9-8717-a334987a0980.png)

동일한 이슈로 보입니다.

**Comment by chamyeongseop** [comment]
안녕하세요. Twitter.pos('팬스타')를 Twitter().pos('팬스타')로 변경해주세요.
