### ISSUE TITLE
숫자(Number)+단위(Noun)를 하나의 명사로 표현 하고 싶습니다.

### ISSUE THREAD

**Issue by whdk999** [lovit/customized_konlpy#22]
문장 형태소를 구분하면 다음과 같이 결과가 나옵니다.

`postprocessor2.pos('이번 상품 구입 갯수는 것은 100개 입니다.')`
`[('이번', 'Noun'),
 ('상품', 'Noun'),
 ('구입', 'Noun'),
 ('갯수', 'Noun'),
 ('는', 'Josa'),
 ('은', 'Josa'),
 **('100', 'Number'),
 ('개', 'Noun'),**
 ('입니다', 'Adjective'),
 ('.', 'Punctuation')]`

형태소가 Number와 Unit 단위인 Noun이 만났을 때 해당 하나의 명사로 표현 될 수 있는지 궁금합니다.
예를들어 다음과 같이 나왔으면 합니다.
('100', 'Number'), ('개', 'Noun') -> ('100개', 'Noun')
('100', 'Number'), ('묶음', 'Noun') -> ('100묶음', 'Noun')

**Comment by midannii** [comment]
> twitter.add_dictionary('100개', 'Count', force=True)

> twitter.add_dictionary('100묶음', 'Noun')

를 이용하여 단어를 추가해보니 아래와 같이 표현됨을 확인할 수 있었습니다 :) 

### twitter.pos('사과 100개 사줘')
 [('사과', 'Noun'), ('100개', 'Count'), ('사줘', 'Verb')]

### twitter.pos('100묶음은 너무 많은데?')
 [('100묶음', 'Noun'), ('은', 'Josa'), ('너무', 'Adverb'), ('많은데', 'Adjective'), ('?', 'Punctuation')]
