### ISSUE TITLE
tutorial의 결과 값이 문서와 다릅니다.

### ISSUE THREAD

**Issue by yuda1124** [lovit/customized_konlpy#6]
안녕하세요. tutorial을 진행하던 중 궁금한 점이 있어 질문 드립니다.
```
def main():
    twitter = Twitter()
    twitter.add_dictionary('이', 'Modifier')
    twitter.add_dictionary('우리', 'Modifier')
    twitter.add_dictionary('이번', 'Modifier')
    twitter.add_dictionary('아이오아이', 'Noun')
    twitter.add_dictionary('행사', 'Noun')
    twitter.add_dictionary('아이', 'Noun')
    twitter.add_dictionary('번것', 'Noun')
    twitter.add_dictionary('것', 'Noun')
    twitter.add_dictionary('은', 'Josa')
    print(twitter._dictionary._pos2words)
    print(twitter.pos('우리아이오아이는 이뻐요'))
```
위 코드를 실행했을 때 결과가
```
{'Modifier': {'이번', '이', '우리'}, 'Noun': {'번것', '것', '아이오아이', '아이', '행사'}, 'Josa': {'은'}}
[('우리', 'Noun'), ('아이오', 'Noun'), ('아이', 'Noun'), ('는', 'Josa'), ('이뻐', 'Adjective'), ('요', 'Eomi')]
```
위와 같이 나왔는데요. 이유를 알기 위해 내부를 본 결과, dictionary에 추가는 되었지만 Score function에서 다른 옵션에 밀리는 점수가 나오는 것을 확인할 수 있었습니다. 

또 정의되어 있지 않은 태그를 새로 정의했던 경우도 비슷한 결과를 받아볼 수 있었는데요.
제가 무엇을 잘못해서 tutorial과 다른 결과값이 나오는 걸까요?
혹시 이미 저장되어있는 word에 다른 tag를 추가하면 기존에 다른 태그에 있던 내용을 삭제하지 않는 이유가 있나요?

**Comment by lovit** [comment]
twitter = Twitter() 에서 KoNLPy 의 Twitter 분석기의 기본 사전을 loading 하는 argument 를 추가했었습니다. 처음 튜토리얼을 만들 때에는 아래와 같았는데, 

class Twitter:
    def __init__(load_default_dictionary=False):
        ....

현재는 아래와 같이 수정이 되었습니다. default 를 True 로 바꿨던 것을 튜토리얼에 반영하지 않았습니다.
또한 이름이 모호하여, use_twitter_dictionary 로 바꿔뒀습니다.
 
class Twitter:
    def __init__(use_twitter_dictionary=True):
        ....

또한 언급해주신대로, 다른 옵션에 점수가 밀립니다. 처음 정의한 score 가 좋지 않아서 발생했던 문제입니다. 명사 중에서는 길이가 가장 긴 명사를 우선 선호하는 것이 더 좋을 것이라 판단 (최장일치법), 이렇게 되도록 고쳐두었습니다.
