### ISSUE TITLE
def nouns 오류가 있습니다.

### ISSUE THREAD

**Issue by Park-Ju-hyeong** [lovit/customized_konlpy#7]
https://github.com/lovit/customized_konlpy/blob/master/ckonlpy/tag/_twitter.py#L46

```
    def nouns(self, phrase):
        tagged = self.pos(phrase)
        return [w for w, t in tagged if t[0] == 'N']
```

tagged  를 w랑 t 로 받은 다음

t[0] 에서 == "N" 으로 명사를 추출하는 방식을 사용하면   Number도 같이 추출이 됩니다.

Konlpy 함수를 참조하면,
t == "Noun" 으로 수정해서 사용하고 있습니다.

**Comment by lovit** [comment]
지적해주신 부분이 맞습니다. t == 'Noun' 으로 수정해두었습니다. 감사함니다.
