### ISSUE TITLE
stopwords, replace를 파일로 등록하는 방법

### ISSUE THREAD

**Issue by parkdk** [lovit/customized_konlpy#8]
stopwords, replace 단어 목록을 txt 파일로 등록/관리하는 방법이 있을까요?

**Comment by lovit** [comment]
ckonlpy.utils.load_wordset 와 ckonlpy.utils.load_replace_wordpair 함수를 만들어 버전 0.0.52 에 넣어뒀습니다.

사용법은 아래와 같습니다.

>>> from ckonlpy.utils import load_wordset
>>> passwords = load_wordset('./passwords.txt')
>>> stopwords = load_wordset('./stopwords.txt')

>>> from ckonlpy.utils import load_replace_wordpair
>>> replace = load_replace_wordpair('./replacewords.txt')
